
# Name of the application that appears in Spring Boot logs
spring.application.name=Application

# Defines how Hibernate creates the database tables.
# create: recreates the tables every time the application starts.
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=create

# Connection URL for MySQL running in Docker on port 3307.
# csd230: name of the database created in docker-compose.yaml
spring.datasource.url=jdbc:mysql://localhost:3307/csd230

#Database user (root), defined in docker-compose.yaml
spring.datasource.username=root

# Database password, also defined in docker-compose.yaml
spring.datasource.password=itstudies12345

#JDBC driver required for Spring Boot to communicate with MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Displays all SQL queries executed by Hibernate in the console.
spring.jpa.show-sql: true

#Hibernate dialect for generating MySQL-compatible SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect